Set colors via config
p00f/nvim-ts-rainbow pull request #31
Opened 2021-05-01 21:25 UTC by c-a-v-a

2021-05-01 22:21 UTC, p00f commented
Can you also change the readme?

2021-05-01 22:24 UTC, p00f commented
Also, please add `termcolors` https://github.com/p00f/nvim-ts-rainbow/blob/11b070c97b0c3908b85f7459398f0a79401fc411/lua/rainbow/internal.lua#L6

2021-05-02 07:59 UTC, c-a-v-a commented
Also I noticed something weird. When I set colors (in colors.lua or in config), they are used out of order. Is this expected behavior, or some kind of bug?

2021-05-02 08:15 UTC, p00f commented
Yeah, this is expected because it counts all nodes for calculating depth. #25 had fixed this but there were other problems I didn't know how to handle at the time so I reverted it. Once I get time I'll do #29 and #25

2021-05-02 08:40 UTC, p00f requested changes

2021-05-02 08:40 UTC, p00f commented on README.md
>  To change the colours, edit `lua/rainbow/colors.lua`. If you want to override only a *few* colours (you can only change colours 1 through 7 this way), you can do it in your init.vim: (thanks @delphin
please delete the first sentence of this line, it is repeated

2021-05-02 08:40 UTC, p00f commented on README.md
>  To change the colours, edit `lua/rainbow/colors.lua`. If you want to override only a *few* colours (you can only change colours 1 through 7 this way), you can do it in your init.vim: (thanks @delphin
(Line 39)

2021-05-02 08:40 UTC, p00f commented on lua/rainbow/internal.lua
>  local termcolors = require("rainbow.termcolors")
This line should be deleted too

2021-05-02 08:40 UTC, p00f commented on lua/rainbow/internal.lua
>  local termcolors = require("rainbow.termcolors")
(` local termcolors = require("rainbow.termcolors")`)

2021-05-02 08:40 UTC, p00f commented on README.md
>  To change the colours, edit `lua/rainbow/colors.lua`. If you want to override only a *few* colours (you can only change colours 1 through 7 this way), you can do it in your init.vim: (thanks @delphin
(To change the colours, edit `lua/rainbow/colors.lua`.)

2021-05-02 08:52 UTC, p00f approved these changes

2021-05-02 08:52 UTC, merged

2021-05-02 08:52 UTC, p00f commented
Thank you very much!